services:
  - type: web
    name: sdcpy-studio
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install --upgrade pip && pip install .
    startCommand: uvicorn sdcpy_studio.main:create_app --factory --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
